[versions]
junit = "5.9.1"
netty = "4.1.94.Final"
mdcfg = "2.0.0-SNAPSHOT"
mdlib = "1.3.1-SNAPSHOT"
slf4j = "2.0.7"
jbr-anno = "24.0.1"
nbt = "1.5.1"

shadow = "8.1.1"
loom = "1.3.8"
multiversion = "0.2.1-SNAPSHOT"
patch = "0.1.1-SNAPSHOT"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
midnight-cfg = { module = "org.wallentines:midnightcfg-api", version.ref="mdcfg" }
midnight-cfg-json = { module = "org.wallentines:midnightcfg-codec-json", version.ref="mdcfg" }
midnight-cfg-gson = { module = "org.wallentines:midnightcfg-codec-gson", version.ref="mdcfg" }
midnight-cfg-binary = { module = "org.wallentines:midnightcfg-codec-binary", version.ref="mdcfg" }
midnight-lib = { module = "org.wallentines:midnightlib", version.ref="mdlib" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref="jbr-anno" }
bitbuf-nbt = { module = "dev.dewy:nbt", version.ref="nbt" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
loom = { id = "fabric-loom", version.ref = "loom" }
multiversion = { id = "org.wallentines.gradle-multi-version", version.ref="multiversion" }
patch = { id = "org.wallentines.gradle-patch", version.ref="patch" }
