[versions]
junit = "5.9.1"
shadow = "8.1.1"
loom = "1.3.8"
netty = "4.1.94.Final"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
loom = { id = "fabric-loom", version.ref = "loom" }